### ISSUE TITLE
Possible hold time issue when latching data from the scanchain

### ISSUE THREAD

**Issue by MichaelBell** [TinyTapeout/tinytapeout-03#3]
Designs normally use `io_in[0]` as a clock.  Naively, one would expect to be able to change the rest of `io_in[7:1]` at the same time as the clock when delivering data to your user project from the scanchain, however doing so seems likely to cause hold time violations if all of `io_in[7:0]` are latched simultaneously.

Because `io_in[0]` is treated as a clock in the configuration, the default `base.sdc` that is being used adds a timing constraint that transitions in the other inputs and outputs are offset by 20% of the clock period - see https://github.com/The-OpenROAD-Project/OpenLane/blob/2023.02.14/scripts/base.sdc#L7

This means we are not getting hold constraint violations from the timing analysis.  However, I don't see anything in the scanchain interface that would actually provide this delay.

I'm new to this code so I may well have missed something - but if not, is there any way that we could add a small delay to the data inputs (and specify the correct timing constraints) to avoid this problem?

**Comment by mattvenn** [comment]
I'll make it clearer in the docs that for clocked designs you should keep data steady on a rising clock edge.
