### ISSUE TITLE
scanchain.v

### ISSUE THREAD

**Issue by WallieEverest** [TinyTapeout/tinytapeout-03#4]
1.) NUM_IOS is undefined when interface is declared. Suggest adding parameter in module definition.

module scanchain #(
  parameter NUM_IOS = 8
)

2.) Add missing port connections to instances.
        .VPB (1'b1),
        .VNB (1'b0)

**Comment by smunaut** [comment]
1) Yes, already fixed in an updated unreleased version
2) What missing connections ? All instances have that AFAICT.
