### ISSUE TITLE
scan_controller.v

### ISSUE THREAD

**Issue by WallieEverest** [TinyTapeout/tinytapeout-03#5]
Signals must be declared before they are used.
Suggest moving line 6 down near line 120, after the wires and reg are defined.
Line 6: assign ready = active && state == ST_IDLE;

State transition table needs a default. Example:
Line 280:  default: state_nxt = ST_IDLE;

**Comment by smunaut** [comment]
Line 6: Yes, not sure how that ended up there, looks like a quick bodge that wasn't fixed.
Line 280: No it doesn't.
