### ISSUE TITLE
scan_controller.v

### ISSUE THREAD

**Issue by WallieEverest** [TinyTapeout/tinytapeout-03#6]
The 'ready' pulse on io_out[37] is the only external indicator of the internal scan clock, and this signal is just 10 ns wide (assuming a 100 MHz Wishbone clock).
Pin buffers might not drive this high-speed signal effectively. Also, many hobbyists do not have equipment for observing 10 ns pulses.
Consider making io_out[37] a toggle of the ready pulse. This more accurately describes the project's maximum clock rate, updating the I/O on the rising and falling edges. The toggle could be used as the interface clock.

**Comment by smunaut** [comment]
The 'slow_clock' debug output on `io[10]` serves that purpose. It's exactly a toggle once every update.
